### ISSUE TITLE
Middleware to Handle Multiple Middlewares

### ISSUE THREAD

**Issue by mwillbanks** [phly/conduit#10]
You should be able to add as many middleware classes as you want (think in terms of having a use() type of thing).  In this case it should be able to look through a stack or a multi-dimensional stack in that case.  (However, the method cannot be named "use" PHP does not like that).

Therefore middleware could add additional middleware through the use of a method that internally changes how the stack is implemented.  The stack should likely pop middleware off and see if it can handle it much like a FIFO buffer.  Items at the beginning of the buffer have the first chance at the stack and thus it's middleware could handle it prior to the next middleware.

Right now the API would be more like $app->pipe('/', $middleware) which may actually handle it properly since it would turn it into a callable and callback but instead of the __invoke it would be handle.  This creates a bit of a small issue.  The other issue is that if it is not found in middleware it returns back a final handler (in which case submiddleware would still need to return next).  It might be possible to check for the result of a FinalHandler and unless it came from the initial stack, it would not utilize it and ignore the response.

From an API perspective, it could make sense to use  $app->utilize($middleware);

Thoughts?

**Comment by moderndeveloperllc** [comment]
I figured it would be better to ask my question here instead of on the apigility-dev mailing list as this issue is directly relevant to [what I asked about there today](https://groups.google.com/a/zend.com/d/msg/apigility-dev/m8PR0qj6q8s/XVgR4RNi1WQJ).

> Once all are executed in that sub-middleware, $next() will move to the next outer middleware.

Does this mean I can do something like:
```
$app = new MiddlewarePipe();
$app->pipe(new Router());
$app->pipe('/customer', new Customer());
$app->pipe(new ResponseDispatch());
$app->pipe(new ErrorHandler());
```
where
```
class Customer extends MiddlewarePipe
{
    public function __construct($configuration) {
        parent::__construct();
        $this->pipe('/new', new HandleNewCustomer());
        $this->pipe('/existing', new HandleExistingCustomer());
    }
}

class CustomMiddleware extends MiddlewarePipe
{
    public function __invoke(Request $request, Response $response, callable $next = null)
    {
        try {
            //Handle New Customer logic
            parent::__invoke($request, $response, $next);
        } catch (Exception $error) {
            $next($request, $response, $error);
        }
    }
}
```

If I'm reading @mwillbanks's question and your reply, a request with a URI of `/customer/new` would have an execution path (assuming no errors) of `Router()->Customer()->HandleNewCustomer()->ResponseDispatch()` and with errors `Router()->Customer()->HandleNewCustomer()->ErrorHandler()`. Flexible, yet ultimately linear, path through the pipeline.

**Comment by weierophinney** [comment]
I'm a little confused by your example, as you don't reference the class CustomMiddleware anywhere when defining your pipeline, and as the class is extending MiddlewarePipe and not another custom subclass. However, yes, your assumption is correct: if you catch an exception, and then call `$next($request, $response, $error)`, `$next` will iterate through the pipeline until if finds the first error handler. Once it does, that error handler can choose whether or not to keep passing responsibility on as well — but it will continue from that specific point in the pipeline.

**Comment by moderndeveloperllc** [comment]
Sorry. I copied/pasted without changing `CustomMiddleware` to `HandleNewCustomer`. It's now updated.

a) I had been unsure as to the nesting for a path like: `/customer/new` –
 `$this->pipe('/new', ...)`, or `$this->pipe('new', ...)`, or `$this->pipe('/customer/new', ...)` inside `Customer`.

b) Am I correct in extending `MiddlewarePipe` and using the `__invoke()` magic function for `HandleNewCustomer()`? This is where the my custom logic/service calls would reside and possibly create new `$request` and `$response` objects to pass down the pipeline.

**Comment by weierophinney** [comment]
@moderndeveloperllc 

(a) When you nest middleware, the child middleware are matched relative to the parent, so your example is correct. The `HandleNewCustomer` middleware will be invoked if the URI matches the path `/customer/new`. That middleware, however, will receive a request instance that only contains the path `/new` (you have to pull the `$request->getOriginalRequest()` instance to get the full URI that actually matched). This is what allows you to reuse middleware by composing and nesting it in your application.

(b) You can extend `MiddlewarePipe`, but it's not necessary; I'd only extend it if I needed to, well, create a pipeline of related middleware. If you're implementing a single middleware, you can either implement the `MiddlewareInterface` or just create some callable that accepts `$request`, `$response`, and, optionally, `$next` (the last is optional if the middleware is terminating).

**Comment by moderndeveloperllc** [comment]
@weierophinney Thanks for answering my questions. I'm starting a small, internal-only, inventory app for the company I'm contracting with. No real specs, no real timeline either. Perfect to try out this library and few other bleeding edge items (Polymer for one). I'll be sure to submit any issues if I come across anything.
