### ISSUE TITLE
Rather than creating an object for middleware what about wrapping in closure?

### ISSUE THREAD

**Issue by harikt** [phly/conduit#17]
Hi Mathew, 

I was wondering what about creating the Middleware object as a closure. That way we could make use of di containers also.

Eg : 

```php
$authMiddleware = new AuthenticationMiddleware($auth, $resume_service);

$app = new Middleware();
$app->pipe('/admin', $authMiddleware);
```

so will be something like 

```php
$app->pipe('/admin', function ($req, $res, $next) use ($auth, $resume_service) {
    return new AuthenticationMiddleware($auth, $resume_service);
});
```

or 

```php
$app->pipe('/admin', function ($req, $res, $next)  {
    return $di->lazyNew('AuthenticationMiddleware');
});
```

**Comment by weierophinney** [comment]
This is already supported - I typehint on callable, not `Middleware`. :-)

**Comment by weierophinney** [comment]
Also, my weierophinney/mwop.net repo uses the exact patterns you describe to lazyload the various composed middleware.

**Comment by harikt** [comment]
I wonder then why it was not working the way I did :/

**Comment by harikt** [comment]
May be it all extends the `Middleware`. I was just passing the `$di->lazyNew` which itself need to be called. Your approach seems a bit different though . I am looking at https://github.com/weierophinney/mwop.net/blob/master/public/index.php#L32-L35

**Comment by harikt** [comment]
ok, I made some changes to make things work.

**Comment by weierophinney** [comment]
Perhaps you could add some examples for the README?

**Comment by harikt** [comment]
@weierophinney I was looking your website. Seems you rewrote it from the static generator. or is it still the same static generated ?

Anyway looks nice. I will look into and try to learn some things and then can look into updating the README or may be a docs folder itself with rst files ?

**Comment by weierophinney** [comment]
@harikt Indeed -- I rewrote the website using Conduit a few months back to test out how it might work using middleware.

I've purposely not spent much time on the Conduit documentation, other than the README, as it has been changing with each minor version, and will likely continue to do so until PSR-7 is voted on. Once I know that the HTTP messages are stable, though, I'd be quite happy to have more documentation, particularly with more usage examples.

**Comment by harikt** [comment]
cool. Thank you.
