### ISSUE TITLE
$this for pipe inside Middleware 

### ISSUE THREAD

**Issue by harikt** [phly/conduit#18]
Hi,

So continuing some more experiments I got some trouble with the pipe inside a middleware. My idea is certain routes may need authentication and certain don't.

Eg : `/admin` , `/blog/edit/{id}` . So this was my middleware 

```php
<?php
namespace Conduit\Middleware;

use Aura\Auth\Auth;
use Aura\Auth\Service\ResumeService;
use Phly\Conduit\Middleware as BaseMiddleware;
use Psr\Http\Message\IncomingRequestInterface as Request;
use Psr\Http\Message\OutgoingResponseInterface as Response;

class AuthenticationMiddleware extends BaseMiddleware
{
    private $auth;

    public function __construct(Auth $auth, ResumeService $resume_service)
    {
        parent::__construct();
        $resume_service->resume($auth);
        $this->auth = $auth;
/*
        $this->pipe('/admin', function ($req, $res, $next) {
            $path = $req->getUrl()->path;
            echo "Second {$path}";
            exit;
        });
*/
        $this->pipe('/admin', $this);
        $this->pipe('/blog', $this);
    }

    public function handle(Request $request, Response $response, callable $next = null)
    {       
        if ($this->auth->isValid()) {
            $next();
        } else {
            $response->setStatus(401);
            $response->setHeader('Location', '/login');
        }
    }
}
```

If I do like `$this->pipe('/admin', $this);` this is never called when I am still in `/admin` . But if I change the pipe to make use of a closure it works. Not sure I am doing the right way.

Thank you

**Comment by weierophinney** [comment]
Try renaming `handle ` to `__invoke` - IIRC, I dropped support for handle a while back, but did not update the docs.

**Comment by harikt** [comment]
ok, I will try and get back to you. Browsing from a different place.

**Comment by harikt** [comment]
Thank you `__invoke` worked.

**Comment by weierophinney** [comment]
Reopening - I need to update the docs to remove the references to the `handle` method.

**Comment by weierophinney** [comment]
Docs were updated with 0.10.0.

**Comment by harikt** [comment]
Apologies for the self promotion.

@weierophinney I have a tool that can read through the repo tags. You can see it http://ghdocs.herokuapp.com/ and can read through `0.1.0`, `0.2.0` etc . See  http://ghdocs.herokuapp.com/phly/conduit/0.1.0/README.md . May be at some point of time someone will like it :) .
