### ISSUE TITLE
Suggestion : pipe

### ISSUE THREAD

**Issue by harikt** [phly/conduit#19]
I think it would be nice if pipe can recognize dynamic route and can add middleware to it.

Eg : `/blog/edit/{id}` . Currently it is possible with `/blog/edit` . May be it seems good to have a built in router which can handler such things?

**Comment by weierophinney** [comment]
No -- I specifically did not include this, for the same reasons that Connect doesn't have that functionality. The basic routing present is primarily for segregating middlewares. As an example, I might have middlewares for:

- a contact form
- a forum
- a blog
- a shopping cart

The basic routing present allows me to attach each of these to a specific base path, and they can then implement their own routing relative to that -- without needing to know what that value is.

As an example, if I do this:

```php
$app->pipe('/cart', $cartMiddleware);
```

then the `$cartMiddleware` can route based on `/` -- it doesn't have to know that the actual URI path starts with `/cart`, as Conduit strips that off in the request passed to it.

That's really the only purpose for the routing in Conduit -- to allow middlewares to perform their own routing relative to a base path.
