### ISSUE TITLE
How do you make a redirect now ?

### ISSUE THREAD

**Issue by harikt** [phly/conduit#20]
Hi, 

I was trying the `0.9` version. Wondering how the redirect works.

This is the code.

```php
$response->withHeader('Location', '/admin')
    ->end();
```

No error has been produced also :-/ . Also as the doc is not up to date could not find it.

**Comment by weierophinney** [comment]
Try:

```php
return $response
    ->withStatus(302)
    ->withHeader('Location', $url);
```

With the new version, you can either return a response, or pass it as an argument to the `$next` callable when you have updates; the former completes the request and ends the application, the latter replaces the response being passed to subsequent middlewares.

**Comment by harikt** [comment]
Hi @weierophinney ,

It did not worked as expected. I am using a controller which is `Login` . So it is not a middleware to return the response though. So I wonder how things will work on it.

May be it needs to check for return values :-/ .

**Comment by harikt** [comment]
This is the code I am trying out https://github.com/harikt/conduit-skelton/pull/8/files#diff-b773213dfc9138c8040c04242181710eR41

**Comment by weierophinney** [comment]
phly/http as of 0.8.0 implements immutable messages. This means you'll need to either return the response and capture the return value in the caller, or reassign the response. Conduit behaves in the way noted above - just make sure on mutation, you reassign (you're not doing so currently in your code, just calling the mutators, which means the updated instance is lost).

**Comment by harikt** [comment]
@weierophinney after working with immutable it seems more time consuming to fix the issue :-/ .

**Comment by harikt** [comment]
Why I think is I have a auth middleware.

```php
$app->pipe('/admin', $di->get('auth_middleware'));
```

What it is doing is 

```php
<?php
public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next = null)
    {
        if ($this->auth->isValid()) {
            return $next();
        } else {
            $response = $response
                ->withStatus(401)
                ->withHeader('Location', '/login');
        }
        return $next($request, $response);
    }
```

Check if it is valid, and call the next middleware. If not it changes the response and call the $next . The problem is now I am getting `Cannot GET http://localhost:8000/admin` .

**Comment by weierophinney** [comment]
>after working with immutable it seems more time consuming to fix the issue

It's hard to adapt code that *was* mutable or used mutable state to immutability; using it from the start is typically straight-forward, and you'll find you make different decisions as a result. Once you get your changes done, you'll get the hang of it, and it will start to feel more natural.

**Comment by harikt** [comment]
may be. But I could not solve the issue even I am returning the changed response :) .

Do you have any idea why this behaves different then ?

**Comment by weierophinney** [comment]
> return $next($request, $response);

This is a case where I'd just return the response, unless you have a later middleware that will return an error page. In that case, pass some sort of error as an argument to `$next` - e.g., an exception with a code of 401 -- and the create an error handler that can render that exception. While I haven't updated mwop.net to the latest http/conduit versions, I do have some authentication middleware that does similarly; you can look there for ideas.

**Comment by harikt** [comment]
Hi @weierophinney , 

I am returning the response https://github.com/harikt/conduit-skelton/pull/8/files#diff-2e9347330c64c8ef35e924f581f3c3d8R38 . I can see the response header contains location for the redirect. But these response headers are some how lost. Not sure where it is lost.

Could find time to check more on the Middleware and Next code.

**Comment by weierophinney** [comment]
Based on twitter feedback, looks like you have this working with 0.10.0. :)

**Comment by harikt** [comment]
Thank you. It works nicely. Sorry, forgot to close it.

**Comment by harikt** [comment]
Hi @weierophinney , 

I think a middleware should call `return` when ever the $next($request, $response); is called.

I was looking to find the reason why the redirect was not working after I made an update to 0.11 of conduit.

**Comment by weierophinney** [comment]
> I think a middleware should call return when ever the $next($request, $response); is called.

I agree, and have noted this in the documentation. I also note that you should either call:

```php
return $next($request, $response);
```

OR

```php
return $response;
```

to ensure the response gets propagated to the top.

**Comment by harikt** [comment]
consider the middleware is a content negotiation one. It should not return response ;) . So should call `return $next` .

**Comment by weierophinney** [comment]
@harikt Exactly — you should _either_ call `return $next(/* ... */);` _or_ call `return $response;`; use the first if there is more processing to accomplish, the second if the response is complete as far as you're concerned.

**Comment by harikt** [comment]
:+1:  .
