### ISSUE TITLE
Semantic: naming of Phly\Conduit\Middleware

### ISSUE THREAD

**Issue by mnapoli** [phly/conduit#24]
Hi there, love what you are doing here.

I just wanted to discuss the naming of `Phly\Conduit\Middleware`. When I first read the readme, I was totally confused by the fact that a middleware is a callable, but at the same time a middleware is an instance of `Phly\Conduit\Middleware`. And worse: you add middlewares on a `Middleware` by calling `pipe()`…

So correct me if I'm wrong, but `Middleware` is actually a sort of "middleware builder", or rather "middleware root" which just so happen to be a callable (which means it's a middleware) right? So would it make sense to name that class differently, maybe with a more specific name to avoid confusion? Or did I miss something?

**Comment by weierophinney** [comment]
The `Middleware` class exists to allow building a stack of middleware... and, because it defines `__invoke` with the expected arguments, is middleware itself. This means you can have a `Middleware` instance as the root of your application:

```php
use Phly\Conduit\Middleware
use Phly\Http\Response;
use Phly\Http\Server;
use Phly\Http\ServerRequest;

// Using Server:
$app = new Middleware();
$server = Server::createServer($app);
$server->listen();

// or as a callable:
$app = new Middleware();
$response = $app(ServerRequestFactory::fromGlobals(), new Response());
// emit the response somehow...
```

Alternately, it can compose/aggregate other middleware, which may or not be instances of `Middleware`:

```php
use Phly\Conduit\Middleware

$app = new Middleware();

$contact = new Middleware();
$contact->pipe('/', function ($req, $res, $next) { });
$contact->pipe('/process', function ($req, $res, $next) { });
$contact->pipe('/thank-you', function ($req, $res, $next) { });
$app->pipe('/contact', $contact);
```

It's not a middleware *builder*, but more of an *aggregator*, with a little extra logic thrown in to ensure that a "final handler" (for handling error conditions) is present if no `$next` callable is provided.

To be honest, I'm not exactly sure what to call it. I settled on `Middleware`, as it can function in that role, but I also see your point that it may be confusing (developers may thing they _must_ extend that class to implement middleware).

I'm open to naming suggestions -- but not Builder. :)

**Comment by mnapoli** [comment]
Yep not "builder" indeed. Why not `MiddlewareStack` as you said it yourself ;) Or `MiddlewareAggregator`?

I understand the definition of a middleware is "a callable that takes X & Y parameters" but since it's not possible to define contracts for callables, would it make sense to define a `Middleware` interface?

I'm guessing most actual implementation of middlewares will be classes (e.g. all StackPHP "middlewares" are classes, especially since all of it is installed with Composer), so an interface would definitely be useful. The interface would be used to provide a strong contract of Middleware implementations, but wouldn't be required of course (since any callable can be a middleware).

**Comment by weierophinney** [comment]
`MiddlewareStack` fits nicely, and is one name I considered -- the name mirrors the design (well, kind of -- technically it's a queue). My primary concern is I don't want it to be confused with StackPHP (which implements lambda-based middleware, vs. message-passing/functional, which Conduit is impelementing). I may go with `MiddlewareQueue`.

Regarding a middleware interface, I've resisted the idea until now. None of Rack, WSGI, or Connect define one; they operate on functions/callables only, and rely on the language to raise errors if the function cannot accept the arguments.

That said, when I talked to @simensen about middleware this past fall, one idea we came up with was having a site or project that would define a number of different middleware styles. (StackPHP started down this trail, but it hasn't really gone anywhere.) Defining an interface here might be a first step towards that -- a project could indicate they implement a particular style of middleware by implementing the interface. It could also lead to some generic "middleware translation" code, that translates from one style to another, allowing you to drop in a wrapper around your own middleware that's compliant with the consuming system.

I'm going to slate these changes for the 0.11.0 release. Thanks for the conversation, @mnapoli !

**Comment by simensen** [comment]
@weierophinney are we going to have a chance to talk in person again soon? or maybe a video chat? it would be nice to sync up again and talk more about middlewares and the future of stack. stack is currently positioned as only working w/ symfony's http kernel interface but i'm planning on talking more about the future of stack and psr http message during my #phpbnl15 talk.

to be blunt, i don't see much future in stack being tied to http kernel interface beyond symfony 2. the tools we've built there should continue to work for as long as symfony 2 is around. if the existing tools work w/ symfony 3 *out of the box* then that will be supported as well. however, i don't see anyone spending more time in continuing to develop stack as a symfony-only project from this point forward.

what i'd like to see is trying to leverage stack as a thing that people may already be associating with middlewares and build out a hub for "php middlewares." perhaps part of that would be writing "stack psr http adapters for symfony" (to continue the symfony legacy) but who knows what will happen there. if psr http message is ready early enough i still have hope that symfony might be able to implement it directly (or provide official adapters) in time for symfony 3's launch at the end of the year.

one can hope, right? :)

**Comment by weierophinney** [comment]
@mnapoli There's actually two interfaces for middleware with the paradigm Connect and Conduit use: normal middleware, which you described, and "error" middleware, which has a different signature:

```php
function ($error, $request, $response, $next)
```

Unfortunately, the arguments are not equivalent, which raises a bit of a concern -- you can `pipe()` either to the middleware queue, and `Next` takes care of determining whether or not they are valid for the current context.

I'm playing around with ideas right now, and will have a PR for you to look at soon.

**Comment by weierophinney** [comment]
> are we going to have a chance to talk in person again soon? or maybe a video chat?

Will you be at SunshinePHP? Otherwise, we can do video chat anytime after your return from Benelux.

**Comment by weierophinney** [comment]
> what i'd like to see is trying to leverage stack as a thing that people may already be associating with middlewares and build out a hub for "php middlewares."

I really like this idea. There's a ton of middleware out there, between the StackPHP and Slim communities, and soon to be flooded with stuff from the Laravel community (and, if all goes as planned, the ZF community). If they can all use PSR-7, or bridges from PSR-7 to the specific HTTP message types can be built, I think we'll see some very cool cross-pollination.

**Comment by weierophinney** [comment]
Please see #29
